version: "3"
services:
  web:
    build: ./.docker
    container_name: project_web
    volumes:
      - ./:/var/www/html
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
